spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # 匹配所有请求
              allowedOrigins: "*" #跨域处理 允许所有的域
              allowedMethods: # 支持的方法
                - GET
                - POST
                - PUT
                - DELETE
      routes:
            - id: dmm_goods_route
              uri: lb://goods
              predicates:
              - Path=/api/goods/**
              filters:
              - StripPrefix=1
              - name: RequestRateLimiter #请求数限流
                args:
                  key-resolver: "#{@ipKeyResolver}"
                  redis-rate-limiter.replenishRate: 10
                  redis-rate-limiter.burstCapacity: 10
            #用户微服务
            - id: dmm_user_route
              uri: lb://user
              predicates:
              - Path=/api/user/**
              filters:
              - StripPrefix=1

            - id: dmm_shoppingCart_route
              uri: lb://shoppingCart
              predicates:
              - Path=/api/cart/**,/api/categoryReport/**
              filters:
              - StripPrefix=1

  application:
    name: gateway
  #Redis配置
  redis:
    host: 192.168.211.132
    port: 6379

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
