spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: fileService
server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka7001/
feign:
  hystrix:
    enabled: true
